name: HoguMeter
options:
  bundleIdPrefix: com.hogumeter
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: ko

settings:
  base:
    PRODUCT_NAME: HoguMeter
    PRODUCT_BUNDLE_IDENTIFIER: com.hogumeter.app
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    SUPPORTS_MACCATALYST: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false

targets:
  HoguMeter:
    type: application
    platform: iOS
    sources:
      - path: HoguMeter
        excludes:
          - "**/.DS_Store"
    info:
      path: HoguMeter/Info.plist
      properties:
        CFBundleDisplayName: 호구미터
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen:
          UIImageName: LaunchImage
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - location
        NSLocationWhenInUseUsageDescription: "호구미터가 주행 거리를 측정하기 위해 위치 정보가 필요합니다."
        NSLocationAlwaysAndWhenInUseUsageDescription: "앱이 백그라운드에서도 주행을 계속 측정하기 위해 위치 정보가 필요합니다."
    settings:
      base:
        INFOPLIST_FILE: HoguMeter/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        ENABLE_PREVIEWS: true
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule

schemes:
  HoguMeter:
    build:
      targets:
        HoguMeter: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
